---
title: "Glossary of terms"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Glossary of terms}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This package seeks to be both accurate and performant, of course. But beyond that, much thought has been put into the readability of the code. Whether being read by a user validating our methods, a developer extending the package to new uses, or a contributor helping enhance the core functionality, we hope that the code contained here can serve as an educational document to grow people's understanding of the graphical approach to multiple comparison procedures.

To that end, there are several entities encountered in the world of graphical MCPs that we define here. Some of these are used only in the internal code of the package, but most are inputs or output in one or more exported functions. If you believe any definitions could be clarified or improved, please contact the package authors or submit an issue to the GitHub repository.

+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| Entity                          | Definition                                                                                                                                                                                                         | Aliases                               | Variable(s)                     | Related                         |
+=================================+====================================================================================================================================================================================================================+=======================================+=================================+=================================+
| **Graph**                       | A set of nodes and edges representing a clinical trial design                                                                                                                                                      |                                       | `graph`                         | Hypotheses, Transitions         |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
|                                 | **Graphs** are so central that two of their core qualities get their own common variable names: Hypothesis names, and number of hypotheses                                                                         |                                       | `hyp_names`, `num_hyps`         |                                 |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Hypotheses**                  | The weighted nodes in a **graph**. Each node represents a null hypothesis corresponding to a treatment endpoint, and its weight the local significance level.                                                      | weights, hypothesis weights           | `hypotheses`                    | Weighting strategy, Transitions |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Transitions**                 | The weighted edges in a **graph**. Each edge defines how to propagate local significance when a source node is deleted.                                                                                            |                                       | `transitions`                   | Hypotheses                      |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Intersection** **hypothesis** | A subset of **hypotheses** from a **graph**. Plural often implies all such subsets.                                                                                                                                | intersection, sub-graph(s), closure   | `intersections`                 | Weighting strategy              |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Weighting strategy**          | The set of all **intersections** and their **weights** according to Algorithm 1 in Bretz et al (2011)                                                                                                              | intersection weights, closure weights | `weighting_strategy`            |                                 |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Adjusted weights**            | The set of **weights**, adjusted according to a testing algorithm:                                                                                                                                                 |                                       | `adjusted_weights`              |                                 |
|                                 |                                                                                                                                                                                                                    |                                       |                                 |                                 |
|                                 | -   Bonferroni: No change                                                                                                                                                                                          |                                       |                                 |                                 |
|                                 | -   Simes: Sum weights for hypotheses with smaller p-values                                                                                                                                                        |                                       |                                 |                                 |
|                                 | -   Parametric: Multiply weights by c-value, based on the joint distribution                                                                                                                                       |                                       |                                 |                                 |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **P-values**                    | The set of p-values from a real or simulated clinical trial                                                                                                                                                        |                                       | `p`                             | Adjusted & ordered p-values     |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Ordered p-values**            | **P-values** sorted from smallest to largest                                                                                                                                                                       |                                       | `ordered_p`                     | (Adjusted) P-values             |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Adjusted p-values**           | **P-values** that have been divided by **adjusted weights**, allowing direct comparison to **alpha** to determine significance                                                                                     |                                       | `adjusted_p`                    | (Ordered) P-values              |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Significance level**          | The threshold chosen for results of a clinical trial to be considered significant                                                                                                                                  |                                       | `alpha`                         | P-values                        |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Test types**                  | A specification of which testing algorithm to use - Bonferroni, Simes, and parametric are supported                                                                                                                | tests                                 | `test_types`                    | Testing strategy                |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Test groups**                 | A partition of nodes in a **graph** specifying which **hypotheses** should be tested together                                                                                                                      | groups                                | `groups`, `test_groups`         | Testing strategy                |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Testing strategy**            | **Test types** and **test groups** combined                                                                                                                                                                        |                                       |                                 |                                 |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Marginal power**              | The power to reject each null **hypothesis** at full **alpha**. Closely related to the non-centrality parameter, which is the mean of each null **hypothesis** in the underlying multivariate normal distribution: |                                       | `marginal_power`                | Correlation matrix              |
|                                 |                                                                                                                                                                                                                    |                                       |                                 |                                 |
|                                 | `ncp = qnorm(1 - alpha) - qnorm(1 - marginal_power)`                                                                                                                                                               |                                       |                                 |                                 |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Correlation matrix**          | Specification of correlations between **hypotheses**. Together with **marginal power**, this specifies the (known or assumed) underlying multivariate normal distribution of the null **hypotheses**.              |                                       | `corr`, `test_corr`, `sim_corr` | Marginal power                  |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Success**                     | A specification of which null **hypotheses** must be rejected to consider a clinical trial a success                                                                                                               |                                       | `sim_success`                   |                                 |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| **Power**                       | Under a given **graph**, **testing strategy**, **significance level**, and underlying distribution, the estimated likelihood that a particular combination of null hypotheses will be rejected                     |                                       | `power_*`                       | Success                         |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| *Delete a **hypothesis***       | Remove a **hypothesis** from a graph, and update the graph according to algorithm 1 of Bretz et al. (2011)                                                                                                         |                                       | N/A                             | Reject a hypothesis             |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
| *Reject a **hypothesis***       | Under a given **graph**, **testing strategy**, and **significance level**, find a hypothesis (clinical endpoint) to be statistically significant, such that the null hypothesis can be rejected                    |                                       |                                 | Delete a hypothesis             |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+---------------------------------+---------------------------------+
