// Generated by cpp11: do not edit by hand
// clang-format off

#include <cpp11/R.hpp>
#include <Rcpp.h>
using namespace Rcpp;
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
list zero_node_cpp(list graph, int remove);
extern "C" SEXP _graphicalMCP_zero_node_cpp(SEXP graph, SEXP remove) {
  BEGIN_CPP11
    return cpp11::as_sexp(zero_node_cpp(cpp11::as_cpp<cpp11::decay_t<list>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(remove)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _graphicalMCP_calcWeightCpp(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_graphicalMCP_calcWeightCpp", (DL_FUNC) &_graphicalMCP_calcWeightCpp, 3},
    {"_graphicalMCP_zero_node_cpp", (DL_FUNC) &_graphicalMCP_zero_node_cpp, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_graphicalMCP(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
