# Generated by cpp11: do not edit by hand

test_graph_shortcut_cpp_ <- function(hypotheses, transitions, p, alpha) {
  .Call(`_graphicalMCP_test_graph_shortcut_cpp_`, hypotheses, transitions, p, alpha)
}

power_shortcut_cpp <- function(hypotheses, transitions, p_mat, alpha) {
  .Call(`_graphicalMCP_power_shortcut_cpp`, hypotheses, transitions, p_mat, alpha)
}
