# Generated by cpp11: do not edit by hand

bonferroni_sequential_cpp <- function(hyps, trns, p, alpha) {
  .Call(`_graphicalMCP_bonferroni_sequential_cpp`, hyps, trns, p, alpha)
}

zero_node_cpp <- function(graph, remove) {
  .Call(`_graphicalMCP_zero_node_cpp`, graph, remove)
}
