# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalculateWeights <- function(h, w, g) {
    .Call(`_graphicalMCP_CalculateWeights`, h, w, g)
}

