# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcWeightCpp <- function(w, g, h) {
    .Call('_graphicalMCP_calcWeightCpp', PACKAGE = 'graphicalMCP', w, g, h)
}

