on:
  pull_request:
    branches: [dev]

name: document

jobs:
  document:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: install packages & document
        shell: Rscript {0}
        run: |
          install.packages("devtools")
          devtools::install(dependencies=TRUE)
          devtools::document()

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add man/\* NAMESPACE DESCRIPTION
          git commit -m "Update documentation" || echo "No changes to commit"
          git pull --ff-only
          git push origin
